### ISSUE TITLE
Editing the README file

### ISSUE THREAD

**Issue by GraceJansen** [OpenLiberty/draft-guide-microprofile-config#13]
An issue to allow us to discuss queries and concerns with the instructions for the microprofile config guide.

**Comment by GraceJansen** [comment]
Would perhaps be nice to include a short explanation at the start, when you introduce the META-INF folder and the microprofile-config.properties file, about the fact that microprofile has three locations in which it can look for static config properties/values (mention bootstrap.properties and server.env) and that this is the default file? I know it is mentioned further down the guide but from experience of learning this topic from scratch, the interactive guide was very helpful in explaining this first before going through one/all of them.

**Comment by GraceJansen** [comment]
As a design question is there a reason that the guide isn't set out using numbers/laying it out in steps?

**Comment by GraceJansen** [comment]
In the guide it does not make it clear that the getPortNumber() method is calling the microprofile-config.properties file. It may be worth pointing this out but that may be adding bulk where it is not necessary so please ignore this if you believe this is the case.

**Comment by GraceJansen** [comment]
In the guide where it says, “modify the existed class”, I believe it should say existing instead of existed.

**Comment by GraceJansen** [comment]
Where is mentions: “Instead of hard coding 9080…”  potentially change the ending of this sentence to something that explains that the above code now allows the port no. to be called from the configuration properties file – providing the externalization of the config value which is beneficial because….?

**Comment by GraceJansen** [comment]
It seems strange to me that the MicroProfile feature being added to the pom.xml and server.xml is the not the first step and is instead after the initial config property has been set up in the properties file. I believe this would make more sense as the first step. That would also leave the explanation about why externalizing config is beneficial as the last section of this segment which I believe would round it off nicely.

**Comment by GraceJansen** [comment]
What is the link at the bottom of the guide for?

**Comment by yeekangc** [comment]
Re "As a design question is there a reason that the guide isn't set out using numbers/laying it out in steps?":  The intention is to keep the guides conversational and speak to developers directly.  Hence, we have tried to do that.

Appropriate organization or numbering may be fine if appropriate but we certainly don't want to turn guides into procedure or formal documentation.  They aren't.

**Comment by evelinec** [comment]
Re "What is the link at the bottom of the guide for?", @JunyiSun can you generate the rendered html for Grace and people to review. I believe that's the common guide section.

**Comment by GraceJansen** [comment]
Thanks YK I've just found where I can see the guide with the rendered HTML on the bluemix OpenLiberty guide site. Can now see all of the code correctly too - much easier.

**Comment by JunyiSun** [comment]
Hi @GraceJansen , Please check the latest guide for the update! Thank you
