### ISSUE TITLE
Feedback on 2/2 Draft

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microprofile-config#34]
Comments based on what is available on test site as of Feb 2.

- [x] "You will learn how to externalize and inject both static and dynamic configuration properties from microservices using MicroProfile Config.":  The "from" should be "for"?

- [x] Then, per what we worked out as a team, the title and abstract should be the below?
Title: Configuring microservices
Abstract: Learn how to provide external configuration to microservices using MicroProfile Config.

- [x] What you'll learn:  I will add a bit more background on what is the application/scenario.  There should be a bit more context before we jump right into the endpoints ...

- [x] Also, in the latest structure we have for the guides, we have _Try what you'll build first_ under _Getting started_?  Should ensure that what is under _What you'll learn_ will come together nicely with _Getting started_ without unnecessary overlap?  @Kubik42 can help review.

- [x] The rest seems fine but I only did a quick pass through them.  May @Kubik42 can do a more detailed review.

- [ ] O yes ... The code needs to sync up with the CDI intro guide.

**Comment by Kubik42** [comment]
Sure I will take a look YK.

**Comment by Kubik42** [comment]
Just took a look. Here is the layout changes that you need to make:
- Add a "Try what you'll build" subsection under the "Getting started" section. In there, walk the user through how to build and run everything and then demonstrate the basic functionality of your app/feature. You can see the cdi guide as an example: https://github.com/OpenLiberty/draft-guide-rest-cdi
- After you add "Try what you'll build", you can remove all the links in the "What you'll learn" section. See the cdi guide for example.
- I think perhaps you should enable the mp-config feature (ie. in the start directory). Same as the pom dependency. Just mention that they exist (by their name).
- You don't need to list `io_openliberty_guides_port_number = 9080` again in a separate listing block. Just state what it is and that its been assigned port 9080.
- I would change all the sentences "Create <filename> file under <path>" to just "Create <path to file>" then a colon (:) followed by the listing block of the file.
- Add a sentence or two after the test results saying what change a user can make to force the tests to fail. But don't be too explicit where to make this change. At this point in the guide, the users should have learned enough to make code changes themselves. It also gives them a good opportunity to debug if they have trouble.
- "Great work, you're done" section needs some next steps (see cdi guide as example).

For now, the layout looks solid. Although you may have to move some stuff around once the side-by-side layout is finalized (but we'll all have to do that anyway).

**Comment by JunyiSun** [comment]
Issues addressed, except for `The code needs to sync up with the CDI intro guide.`

**Comment by JunyiSun** [comment]
Create a new issue with the left over one: The code needs to sync up with the CDI intro guide.

**Comment by evelinec** [comment]
@JunyiSun This didn't seem being addressed:

- [ ] I would change all the sentences "Create <filename> file under <path>" to just "Create <path to file>" then a colon (:) followed by the listing block of the file.
