### ISSUE TITLE
Referencing CustomConfigSource.java

### ISSUE THREAD

**Issue by Ahmad-Ayyoub** [OpenLiberty/draft-guide-microprofile-config#41]
There should be a better way than referencing CustomConfigSource.json from InventoryConfig or ConfigurationTest.java 

previously it was : 

String fileLocation = System.getProperty("user.dir").split("finish")[0]
      + "resources/CustomConfigSource.json";

my quick fix (now): 

String fileLocation = System.getProperty("user.dir").split("target")[0]
      + "../resources/CustomConfigSource.json";

we should look into a better way for referencing this file

**Comment by evelinec** [comment]
@JunyiSun pls review this change and work it out with @Ahmad-Ayyoub. Thanks.

**Comment by JunyiSun** [comment]
@evelinec I think Ahmad has merged this change to master already, although I am not sure what the real issue is. The change seems not to make any difference to the code.

**Comment by JunyiSun** [comment]
Fixed by https://github.com/OpenLiberty/draft-guide-microprofile-config/commit/3538e6bec805f331dd01e7cf0bbab08a50ef8367
