### ISSUE TITLE
Continue to investigate the ConfigSource consultation delay 

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-microprofile-config#44]
We need to continue investigating to understand the ConfigSource consultation delay between 17003 and 17004. Detail in #43.

**Comment by evelinec** [comment]
@gkertaseferi adding Gkerta to help communicate with Tom.

**Comment by gkertaseferi** [comment]
After talking to @Emily-Jiang we concluded that 17003 and 17004 are almost the same and config is not perfectly designed in any of them. In both versions, for the server to observe the changes we need at least 500 milliseconds. That's why we need to add a delay of a bit more than 500 milliseconds.
