### ISSUE TITLE
Common adoc for getting started section

### ISSUE THREAD

**Issue by GraceJansen** [OpenLiberty/draft-guide-microprofile-config#45]
Need to put the common adocs, ie, gitclone, mvnbuild, mvnpackage, mvnverify, finish, etc back to this guide. For example, add include::{common-includes}/gitclone.adoc[] right after the == Getting started section. @evelinec @JunyiSun  This is the same issue as the FT guide

**Comment by JunyiSun** [comment]
Fixed by #46 , you can close this issue. @GraceJansen
