### ISSUE TITLE
User review (second round)

### ISSUE THREAD

**Issue by JunyiSun** [OpenLiberty/draft-guide-microprofile-config#49]
From Anna:

I had no issues with the Config guide and followed through with the instructions, everything is clear. Th only thing is I get a test failure when I run `mvn verify` for the ConfigurationTest. Here is the failure report:
 
-------------------------------------------------------------------------------
Test set: it.io.openliberty.guides.config.ConfigurationTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.011 sec <<< FAILURE! - in it.io.openliberty.guides.config.ConfigurationTest
testSuite(it.io.openliberty.guides.config.ConfigurationTest)  Time elapsed: 3.01 sec  <<< FAILURE!
org.junit.ComparisonFailure: io_openliberty_guides_testConfigOverwrite should be CustomSource in the end expected:<[Custom]Source> but was:<[Default]Source>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at it.io.openliberty.guides.config.ConfigurationTest.testOverrideConfigProperty(ConfigurationTest.java:97)
    at it.io.openliberty.guides.config.ConfigurationTest.testSuite(ConfigurationTest.java:63)
 
That was the only issue.

**Comment by JunyiSun** [comment]
This issue is fixed by investigating on Anna's local repo, we found out that she didn't complete this step in the guide so the test failed.

"To register the custom configuration source, create a `start/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource` file and add the full class name into it"

**Comment by yeekangc** [comment]
Great.  We should make it clearer at the very minimum.  Thanks.

**Comment by JunyiSun** [comment]
Fixed by #50
