### ISSUE TITLE
Confusing instructions

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microprofile-config#51]
(1) Should advise users to copy all the code and replace the content of the file as a simple way forward

_To use externalized configuration in the inventory service, open the src/main/java/io/openliberty/guides/inventory/InventoryResource.java file. Modify the existing class to finalize the code as the following:_

Should do so wherever the code has been provided i.e. non-empty file and users are asked to modify them.

(2) Remind users where they should run mvn commands

**Comment by JunyiSun** [comment]
First issue has been fixed, the second issue should be fixed through guide-common
